### ISSUE TITLE
Not working for me

### ISSUE THREAD

**Issue by samskiter** [RadiusNetworks/bluetooth-crash-resolver#6]
Have tried the force flush from the app on the app store on a Galaxy S3 and an XPeria Z1 and had no luck on either - bluetooth will still crash as soon as an LeScan is performed. Have tried running the app in the presence of beacons and without and have also tried with `TIME_TO_LET_DISCOVERY_RUN_MILLIS=0`

The debug shows everything seems to be working in terms of detecting crashes and kicking off discoveries, but that doesn't seem to be clearing the list. Any other tips?

**Comment by davidgyoung** [comment]
Sorry for the trouble!  I have heard reports of the tool not working on those phones before.  Some manufacturers customize the Bluetooth stack in their firmware making the technique not work for unknown reasons.  Because the customized firmware is not open source, it is hard to troubleshoot.

If you can get root access to the phones, I can provide instructions for clearing the condition using an adb shell.  Obviously, thiis is not an easy solution.

**Comment by samskiter** [comment]
Ah ok. Shame as the S3 is a popular phone AND is likely to be stuck on old versions

**Comment by davidgyoung** [comment]
Agreed.  Unfortunately, I don't have a S3 on 4.x to test with.  I'd be glad to work with you on adding support if you can root the phone and do some testing.
